### ISSUE TITLE
clear `refSticker` on highlight when you delete the sticker from highlight.

### ISSUE THREAD

**Issue by BenBBear** [beenote-ucsd/beenote#27]
Prevent the exception from removeById, although it won't influence the program execution.

**Comment by Vectorlee** [comment]
Here we need to consider two different cases:
1. user delete the highlight: then we need to delete both highlight and the connected sticker note.
2. user delete the sticker note: then we need to delete the sticker note, then clean the refSticker reference in the highlight, and **save the highlight to the database**, since we actually changed it.

**Comment by Vectorlee** [comment]
Bug fixed ~
